### ISSUE TITLE
Preserve state

### ISSUE THREAD

**Issue by jkuss** [MeoMix/antfarm#1]
I'd like my ant farm to pause when I close the tab so that I can return to it without starting over. This may also necessitate a "start over" control. 

This also impacts the philosophy of the game (ephemeral, "watcher not owner", permanence, etc) so any discussion is welcome.

**Comment by MeoMix** [comment]
Implemented! 

World state saves once a minute automatically just in case browser crashes. Saves when tab is closed. There's now an app bar w/ settings dialog that has the ability to delete save and start the world over.
